name: example_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  get_it: ^8.2.0
  go_router: ^16.1.0
  flutter_bloc: ^9.1.1
  dio: ^5.9.0
  dartz: ^0.10.1
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.2

flutter:
  uses-material-design: true
